version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  
  client: # name of the first service
    build: ./angular-client # specify the directory of the Dockerfile
    volumes:
      # mounts local source code to container
      - ./angular-client:/usr/src/app
      # mounts node modules to container
      - ./angular-client/node_modules
    ports:
      - "4200:4200" # specify port forwarding
      - "49153:49153" # specify port for hot reload

  server: #name of the second service
    build: ./express-server # specify the directory of the Dockerfile
    volumes:
      # mounts local source code to container
      - ./express-server:/usr/src/app
      # mounts node modules to container
      - ./express-server/node_modules
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding